import os


BOT_TOKEN = os.getenv('TELEGRAM_TOKEN')

DOMAIN_SERVICE_URL = os.getenv('DOMAIN_URL')

API_SECRET_KEY = os.getenv('API_SECRET_KEY')

TELEGRAM_WEBHOOK_URL = os.getenv('TELEGRAM_WEBHOOK_URL')